//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.30 at 03:08:13 PM IST 
//


package com.iexceed.appzillon.jaxb;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AccountMasterQueryRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountMasterQueryRes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CurrentBal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="LineAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ClearingAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="WithdrawableBal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="CreationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="LastTransactionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AccountAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Error" type="{http://www.iexceed.com/ErrorNode}ComplexError"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountMasterQueryRes", propOrder = {
    "accountNum",
    "accountName",
    "accountType",
    "accountCurrency",
    "currentBal",
    "lineAmt",
    "clearingAmt",
    "withdrawableBal",
    "creationDate",
    "lastTransactionDate",
    "accountAddress",
    "customerId",
    "error"
})
@XmlRootElement(name="AccountMasterQueryRes", namespace = "http://www.iexceed.com/AccountMasterQueryRes")
public class AccountMasterQueryRes implements Serializable{

    @XmlElement(name = "AccountNum", required = true)
    protected String accountNum;
    @XmlElement(name = "AccountName", required = true)
    protected String accountName;
    @XmlElement(name = "AccountType", required = true)
    protected String accountType;
    @XmlElement(name = "AccountCurrency", required = true)
    protected String accountCurrency;
    @XmlElement(name = "CurrentBal", required = true)
    protected BigDecimal currentBal;
    @XmlElement(name = "LineAmt", required = true)
    protected BigDecimal lineAmt;
    @XmlElement(name = "ClearingAmt", required = true)
    protected BigDecimal clearingAmt;
    @XmlElement(name = "WithdrawableBal", required = true)
    protected BigDecimal withdrawableBal;
    @XmlElement(name = "CreationDate", required = true)
    @XmlSchemaType(name = "date")
    protected Date creationDate;
    @XmlElement(name = "LastTransactionDate", required = true)
    @XmlSchemaType(name = "date")
    protected Date lastTransactionDate;
    @XmlElement(name = "AccountAddress", required = true)
    protected String accountAddress;
    @XmlElement(name = "CustomerId", required = true)
    protected String customerId;
    @XmlElement(name = "Error", required = true)
    protected ComplexError error;

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the accountCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCurrency() {
        return accountCurrency;
    }

    /**
     * Sets the value of the accountCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCurrency(String value) {
        this.accountCurrency = value;
    }

    /**
     * Gets the value of the currentBal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentBal() {
        return currentBal;
    }

    /**
     * Sets the value of the currentBal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentBal(BigDecimal value) {
        this.currentBal = value;
    }

    /**
     * Gets the value of the lineAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineAmt() {
        return lineAmt;
    }

    /**
     * Sets the value of the lineAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineAmt(BigDecimal value) {
        this.lineAmt = value;
    }

    /**
     * Gets the value of the clearingAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getClearingAmt() {
        return clearingAmt;
    }

    /**
     * Sets the value of the clearingAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setClearingAmt(BigDecimal value) {
        this.clearingAmt = value;
    }

    /**
     * Gets the value of the withdrawableBal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWithdrawableBal() {
        return withdrawableBal;
    }

    /**
     * Sets the value of the withdrawableBal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWithdrawableBal(BigDecimal value) {
        this.withdrawableBal = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(Date value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the lastTransactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getLastTransactionDate() {
        return lastTransactionDate;
    }

    /**
     * Sets the value of the lastTransactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastTransactionDate(Date value) {
        this.lastTransactionDate = value;
    }

    /**
     * Gets the value of the accountAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountAddress() {
        return accountAddress;
    }

    /**
     * Sets the value of the accountAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountAddress(String value) {
        this.accountAddress = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexError }
     *     
     */
    public ComplexError getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexError }
     *     
     */
    public void setError(ComplexError value) {
        this.error = value;
    }

	@Override
	public String toString() {
		return "AccountMasterQueryRes [accountNum=" + accountNum
				+ ", accountName=" + accountName + ", accountType="
				+ accountType + ", accountCurrency=" + accountCurrency
				+ ", currentBal=" + currentBal + ", lineAmt=" + lineAmt
				+ ", clearingAmt=" + clearingAmt + ", withdrawableBal="
				+ withdrawableBal + ", creationDate=" + creationDate
				+ ", lastTransactionDate=" + lastTransactionDate
				+ ", accountAddress=" + accountAddress + ", customerId="
				+ customerId + ", error=" + error + "]";
	}

}
